swagger: '2.0'
info:
  title: API_ID optional-string
  description: Sample API on API Gateway with a Google Cloud Functions backend
  version: 1.0.0
schemes:
  - https
produces:
  - application/json
paths:
  /hello:
    get:
      summary: Hello world
      operationId: hello
      x-google-backend:
        address: ${address.default}
      responses:
        '200':
          description: A successful response
          schema:
            type: string
